modname = uicontrols
get_path = libvis-mods where
front_src = $(shell $(get_path) --front)
back_src = $(shell $(get_path) --back)

install:
	libvis_mods install

requirements:
	@echo "Installed requirements"




