name: Docs

on:
  push:
    paths:
      - ".github/**"
      - "python/**"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: build docs
      run: |
          python3 python/setup.py develop --user
          cd python/docs
          make html
